/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/library.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/library.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.001']} position={[-7.838, 5.823, -0.004]} rotation={[-Math.PI, 0, 0]} scale={[-0.616, -0.045, -2.743]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.001']} position={[-8.34, 5.417, 1.727]} scale={[1.138, 1.087, 0.917]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Ceiling} position={[0, 11.019, 0]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-2.076, 1.437, 9.111]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.002']} position={[-5.002, 0.128, -0.133]} scale={[1, 0.031, 0.402]} />
        <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[-0.679, 5.775, -0.181]} rotation={[0, 0, -0.118]} scale={[0.114, 0.723, 0.471]} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.002']} position={[7.569, 0.128, -0.133]} scale={[1, 0.031, 0.402]} />
        <mesh geometry={nodes.Cube006.geometry} material={materials['Material.002']} position={[1.284, 0.128, -0.133]} scale={[1, 0.031, 0.402]} />
        <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[-5.7, -12.997, -0.331]} />
      </mesh>
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[9.443, -1.289, -0.015]} scale={0.383} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.003']} position={[0, 5.733, 0]} scale={[9, 5.5, 9]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Carpet} position={[8, 0.447, -0.136]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.006']} position={[-9.486, 1.437, 0]} scale={[1.25, 1, 3.6]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.005']} position={[-8.363, 6.967, 5.967]} scale={[0.413, 3.846, 1.703]} />
      <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} />
      <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} />
      <mesh geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} />
      <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} />
      <mesh geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} />
    </group>
  )
}

useGLTF.preload('/library.glb')
