/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/library.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LibraryModel(props) {
  const { nodes, materials } = useGLTF('./models/library.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.001']} position={[-7.838, 5.823, -0.004]} rotation={[-Math.PI, 0, 0]} scale={[-0.616, -0.045, -2.743]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.001']} position={[-8.34, 5.417, 1.727]} scale={[1.138, 1.087, 0.917]} />
      
      
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[9.443, -1.289, -0.015]} scale={0.383} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.003']} position={[0, 5.733, 0]} scale={[9, 5.5, 9]} />
    
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.006']} position={[-9.486, 1.437, 0]} scale={[1.25, 1, 3.6]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.005']} position={[-8.363, 6.967, 5.967]} scale={[0.413, 3.846, 1.703]} />
 
    </group>
  )
}

useGLTF.preload('./models/library.glb')
