/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/library222.glb 
*/

import React, { useRef, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useGLTF, useAnimations, Html } from "@react-three/drei";
import { useControls } from "leva";
import * as THREE from "three";
import "../styles/LibraryModel.css";
import WordlePNG from "../assets/Wordle.png";
import "../styles/LibraryPage.css";

export function LibraryModel({ shelf, setShelf, ...props }) {
  const group = useRef();
  const navigate = useNavigate();
  const { nodes, materials, animations } = useGLTF("./models/library222.glb");
  const { actions } = useAnimations(animations, group);
  const [hovered, setHovered] = useState(false);
  const [originalMaterial, setOriginalMaterial] = useState(null);

  useEffect(() => {
    // Perform any actions based on the shelf change
    if (typeof shelf === "string") {
      console.log(`LibraryModel received shelf: ${shelf}`);
      // Add your logic here to respond to the shelf change
    }
  }, [shelf]);

  const { animation } = useControls({
    animation: {
      value: "Idle",
      options: Object.keys(actions),
    },
  });

  useEffect(() => {
    if (actions[animation]) {
      actions[animation].setLoop(THREE.LoopOnce, 1); // Play only once
      actions[animation].clampWhenFinished = true; // Stop at the last frame
      actions[animation].play();
    }
    return () => {
      if (actions[animation]) {
        actions[animation].stop();
      }
    };
  }, [animation]);

  const handleMouseEnter = (event) => {
    /* const object = event.object;
    if (!originalMaterial) {
      setOriginalMaterial(object.material.clone());
    }
    object.material.emissive = new THREE.Color(0xffff00); // Highlight color
    */
    setHovered(true);
    document.body.style.cursor = "pointer";
    event.stopPropagation();
  };

  const handleMouseLeave = (event) => {
    /*
    const object = event.object;
    if (originalMaterial) {
      object.material.emissive = originalMaterial.emissive.clone();
    }
    */
    setHovered(false);
    document.body.style.cursor = "default";
    event.stopPropagation();
  };

  useEffect(() => {
    const animationName = "Book2_ClosedAction.002";
    if (hovered && actions[animationName]) {
      actions[animationName].setLoop(THREE.LoopOnce, 1); // Play only once
      actions[animationName].clampWhenFinished = true; // Stop at the last frame
      actions[animationName].reset().play();
    } else if (actions[animationName]) {
      actions[animationName].stop();
    }
  }, [hovered]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="RootNode"
          position={[-5.26, 1.468, 6.012]}
          rotation={[-Math.PI, 1.231, -Math.PI]}
          scale={2.855}
        >
          <group
            name="ClubArmChair1001"
            position={[4.255, 0, 0.895]}
            rotation={[-Math.PI / 2, 0, -1.017]}
            scale={100}
          >
            <mesh
              name="ClubArmChair1003"
              geometry={nodes.ClubArmChair1003.geometry}
              material={materials.ClubArmChair}
            />
            <mesh
              name="ClubArmChair1003_1"
              geometry={nodes.ClubArmChair1003_1.geometry}
              material={materials.WoodClucArmChair}
            />
          </group>
          <group
            name="ClubArmChair1002"
            position={[0.283, 0, -0.532]}
            rotation={[-Math.PI / 2, 0, 0.131]}
            scale={100}
          >
            <mesh
              name="ClubArmChair1004"
              geometry={nodes.ClubArmChair1004.geometry}
              material={materials.ClubArmChair}
            />
            <mesh
              name="ClubArmChair1004_1"
              geometry={nodes.ClubArmChair1004_1.geometry}
              material={materials.WoodClucArmChair}
            />
          </group>
          <mesh
            name="Pad1ClubArmChair1001"
            geometry={nodes.Pad1ClubArmChair1001.geometry}
            material={materials.PadClubArmChair1}
            position={[4.257, 0.008, 0.893]}
            rotation={[-Math.PI / 2, 0, -1.017]}
            scale={100}
          />
          <mesh
            name="Pad1ClubArmChair1002"
            geometry={nodes.Pad1ClubArmChair1002.geometry}
            material={materials.PadClubArmChair1}
            position={[0.282, 0.008, -0.535]}
            rotation={[-Math.PI / 2, 0, 0.131]}
            scale={100}
          />
        </group>
        <group
          name="RootNode001"
          position={[-2.105, 6.454, -8.229]}
          rotation={[0, 1.571, 0]}
          scale={1.839}
        >
          <group
            name="Candle001"
            position={[0.014, -0.057, -3.403]}
            rotation={[0, 0, 0.167]}
            scale={109.128}
          >
            <mesh
              name="Candle001_1"
              geometry={nodes.Candle001_1.geometry}
              material={materials["mat21.001"]}
            />
            <mesh
              name="Candle001_2"
              geometry={nodes.Candle001_2.geometry}
              material={materials["mat17.001"]}
            />
            <mesh
              name="Candle001_3"
              geometry={nodes.Candle001_3.geometry}
              material={materials.mat13}
            />
            <mesh
              name="Candle001_4"
              geometry={nodes.Candle001_4.geometry}
              material={materials["mat12.001"]}
            />
          </group>
          <group
            name="Candle003"
            position={[0.014, -0.057, 3.396]}
            rotation={[0, 0, 0.167]}
            scale={109.128}
          >
            <mesh
              name="Candle004"
              geometry={nodes.Candle004.geometry}
              material={materials["mat21.001"]}
            />
            <mesh
              name="Candle004_1"
              geometry={nodes.Candle004_1.geometry}
              material={materials["mat17.001"]}
            />
            <mesh
              name="Candle004_2"
              geometry={nodes.Candle004_2.geometry}
              material={materials.mat13}
            />
            <mesh
              name="Candle004_3"
              geometry={nodes.Candle004_3.geometry}
              material={materials["mat12.001"]}
            />
          </group>
        </group>
        <group name="RootNode002" position={[-7.869, 5.871, 2.004]}>
          <group
            name="Candles_1"
            rotation={[-Math.PI / 2, 0, 2.805]}
            scale={9.909}
          >
            <mesh
              name="Candles_1_1"
              geometry={nodes.Candles_1_1.geometry}
              material={materials.Candle}
            />
            <mesh
              name="Candles_1_2"
              geometry={nodes.Candles_1_2.geometry}
              material={materials.Light}
            />
            <mesh
              name="Candles_1_3"
              geometry={nodes.Candles_1_3.geometry}
              material={materials.Black}
            />
          </group>
        </group>
        <group
          name="RootNode003"
          position={[0, 7.154, 0]}
          onPointerOver={(e) => {
            handleMouseEnter(e);
          }}
          onPointerOut={(e) => {
            handleMouseLeave(e);
          }}
          onClick={() => navigate("/library/games")}
        >
          <group
            name="Book2_Closed001"
            position={[3.596, -0.017, 8.866]}
            rotation={[-1.599, 0.129, 0.004]}
            scale={[132.303, 151.256, 151.151]}
          >
            <mesh
              name="Book2_Closed001_1"
              geometry={nodes.Book2_Closed001_1.geometry}
              material={materials.DarkRed}
              userData={{ isHtml: false }}
            />
            <mesh
              name="Book2_Closed001_2"
              geometry={nodes.Book2_Closed001_2.geometry}
              material={materials.Golden}
              userData={{ isHtml: false }}
            />
            <mesh
              name="Book2_Closed001_3"
              geometry={nodes.Book2_Closed001_3.geometry}
              material={materials.Beige}
              userData={{ isHtml: false }}
            />
          </group>
          {hovered && (
            <Html position={[4.47, 0.5, 8.866]}>
              <div
                className="hover-info"
                onMouseEnter={(e) => e.stopPropagation()}
                onMouseLeave={(e) => e.stopPropagation()}
              >
                <h3>Wordle</h3>
                <img src={WordlePNG} />
              </div>
            </Html>
          )}
        </group>
        <mesh
          name="Cube015"
          geometry={nodes.Cube015.geometry}
          material={materials["Wood Pillars"]}
          position={[-7.838, 5.823, -0.004]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.616, -0.045, -2.743]}
        />
        <mesh
          name="Cube016"
          geometry={nodes.Cube016.geometry}
          material={materials["Wood Pillars"]}
          position={[-8.34, 5.417, 1.727]}
          scale={[1.138, 1.087, 0.917]}
        />
        <mesh
          name="Plane001"
          geometry={nodes.Plane001.geometry}
          material={materials["Wood Ceiling"]}
          position={[0, 11.019, 0]}
        />
        <mesh
          name="Cube017"
          geometry={nodes.Cube017.geometry}
          material={materials["Wood Pillars"]}
          position={[-5.982, 10.824, -9.122]}
          scale={[0.494, 0.35, 0.35]}
        />
        <mesh
          name="Cube018"
          geometry={nodes.Cube018.geometry}
          material={materials["Wood Pillars"]}
          position={[-7.366, 10.039, 3.155]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1.419, 1.383, 1.658]}
        />
        <mesh
          name="Cube019"
          geometry={nodes.Cube019.geometry}
          material={materials["Wood Pillars"]}
          position={[-5.966, 9.582, 8.572]}
          scale={[1.419, 1.247, 1.658]}
        />
        <mesh
          name="Cube020"
          geometry={nodes.Cube020.geometry}
          material={materials["Wood Pillars"]}
          position={[0.83, 9.582, 8.572]}
          scale={[1.419, 1.247, 1.658]}
        />
        <mesh
          name="Cube021"
          geometry={nodes.Cube021.geometry}
          material={materials["Wood Pillars"]}
          position={[7.646, 9.582, 8.572]}
          scale={[1.419, 1.247, 1.658]}
        />
        <group
          name="group1222719261"
          position={[-8.371, 2.737, -4.386]}
          rotation={[-Math.PI, 1.373, -Math.PI]}
          scale={[4.557, 6.162, 4.557]}
        >
          <mesh
            name="mesh1222719261"
            geometry={nodes.mesh1222719261.geometry}
            material={materials["mat16.001"]}
          />
          <mesh
            name="mesh1222719261_1"
            geometry={nodes.mesh1222719261_1.geometry}
            material={materials.mat15}
          />
          <mesh
            name="mesh1222719261_2"
            geometry={nodes.mesh1222719261_2.geometry}
            material={materials.mat20}
          />
          <mesh
            name="mesh1222719261_3"
            geometry={nodes.mesh1222719261_3.geometry}
            material={materials.mat12}
          />
        </group>
        <group
          name="campfire_01_Plane003"
          position={[-9.425, 0.532, 0.034]}
          scale={0.371}
        >
          <mesh
            name="campfire_01_Plane003-Mesh"
            geometry={nodes["campfire_01_Plane003-Mesh"].geometry}
            material={materials.FF5722}
          />
          <mesh
            name="campfire_01_Plane003-Mesh_1"
            geometry={nodes["campfire_01_Plane003-Mesh_1"].geometry}
            material={materials["78909C"]}
          />
          <mesh
            name="campfire_01_Plane003-Mesh_2"
            geometry={nodes["campfire_01_Plane003-Mesh_2"].geometry}
            material={materials.FFCC88}
          />
          <mesh
            name="campfire_01_Plane003-Mesh_3"
            geometry={nodes["campfire_01_Plane003-Mesh_3"].geometry}
            material={materials.FFEB3B}
          />
          <mesh
            name="campfire_01_Plane003-Mesh_4"
            geometry={nodes["campfire_01_Plane003-Mesh_4"].geometry}
            material={materials["795548"]}
          />
          <mesh
            name="campfire_01_Plane003-Mesh_5"
            geometry={nodes["campfire_01_Plane003-Mesh_5"].geometry}
            material={materials.CFD8DC}
          />
        </group>
        <mesh
          name="Cube007"
          geometry={nodes.Cube007.geometry}
          material={materials["Material.002"]}
          position={[-8.397, 8.254, -0.004]}
          scale={[0.059, 1.612, 1.612]}
        />
        <group
          name="group59889140"
          position={[-4.164, 8.717, 8.835]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh59889140"
            geometry={nodes.mesh59889140.geometry}
            material={materials["mat17.002"]}
          />
          <mesh
            name="mesh59889140_1"
            geometry={nodes.mesh59889140_1.geometry}
            material={materials["mat21.002"]}
          />
        </group>
        <group
          name="group519634257"
          position={[-4.164, 8.717, 8.835]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh519634257"
            geometry={nodes.mesh519634257.geometry}
            material={materials["mat21.002"]}
          />
          <mesh
            name="mesh519634257_1"
            geometry={nodes.mesh519634257_1.geometry}
            material={materials["mat8.001"]}
          />
          <mesh
            name="mesh519634257_2"
            geometry={nodes.mesh519634257_2.geometry}
            material={materials["mat23.001"]}
          />
        </group>
        <group
          name="group1274572461"
          position={[-4.164, 8.717, 8.835]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh1274572461"
            geometry={nodes.mesh1274572461.geometry}
            material={materials["mat12.002"]}
          />
          <mesh
            name="mesh1274572461_1"
            geometry={nodes.mesh1274572461_1.geometry}
            material={materials["mat21.002"]}
          />
        </group>
        <group
          name="group1445929716"
          position={[-4.164, 8.717, 8.835]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh1445929716"
            geometry={nodes.mesh1445929716.geometry}
            material={materials["mat21.002"]}
          />
          <mesh
            name="mesh1445929716_1"
            geometry={nodes.mesh1445929716_1.geometry}
            material={materials["mat3.001"]}
          />
        </group>
        <group
          name="group824283698"
          position={[-4.164, 8.717, 8.835]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh824283698"
            geometry={nodes.mesh824283698.geometry}
            material={materials["mat21.002"]}
          />
          <mesh
            name="mesh824283698_1"
            geometry={nodes.mesh824283698_1.geometry}
            material={materials["mat20.001"]}
          />
          <mesh
            name="mesh824283698_2"
            geometry={nodes.mesh824283698_2.geometry}
            material={materials["mat12.002"]}
          />
        </group>
        <group
          name="group624951879"
          position={[-4.164, 8.717, 8.835]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh624951879"
            geometry={nodes.mesh624951879.geometry}
            material={materials.mat9}
          />
          <mesh
            name="mesh624951879_1"
            geometry={nodes.mesh624951879_1.geometry}
            material={materials["mat21.002"]}
          />
        </group>
        <group
          name="group59889140001"
          position={[-3.95, 8.717, 8.835]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh59889140001"
            geometry={nodes.mesh59889140001.geometry}
            material={materials["mat17.002"]}
          />
          <mesh
            name="mesh59889140001_1"
            geometry={nodes.mesh59889140001_1.geometry}
            material={materials["mat21.002"]}
          />
        </group>
        <group
          name="group59889140002"
          position={[-0.688, 8.709, -9.035]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh59889140002"
            geometry={nodes.mesh59889140002.geometry}
            material={materials["mat17.002"]}
          />
          <mesh
            name="mesh59889140002_1"
            geometry={nodes.mesh59889140002_1.geometry}
            material={materials["mat21.002"]}
          />
        </group>
        <group
          name="group519634257001"
          position={[-0.688, 8.709, -9.035]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh519634257001"
            geometry={nodes.mesh519634257001.geometry}
            material={materials["mat21.002"]}
          />
          <mesh
            name="mesh519634257001_1"
            geometry={nodes.mesh519634257001_1.geometry}
            material={materials["mat8.001"]}
          />
          <mesh
            name="mesh519634257001_2"
            geometry={nodes.mesh519634257001_2.geometry}
            material={materials["mat23.001"]}
          />
        </group>
        <group
          name="group1274572461001"
          position={[-0.688, 8.709, -9.035]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh1274572461001"
            geometry={nodes.mesh1274572461001.geometry}
            material={materials["mat12.002"]}
          />
          <mesh
            name="mesh1274572461001_1"
            geometry={nodes.mesh1274572461001_1.geometry}
            material={materials["mat21.002"]}
          />
        </group>
        <group
          name="group1445929716001"
          position={[-0.688, 8.709, -9.035]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh1445929716001"
            geometry={nodes.mesh1445929716001.geometry}
            material={materials["mat21.002"]}
          />
          <mesh
            name="mesh1445929716001_1"
            geometry={nodes.mesh1445929716001_1.geometry}
            material={materials["mat3.001"]}
          />
        </group>
        <group
          name="group824283698001"
          position={[-0.688, 8.709, -9.035]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh824283698001"
            geometry={nodes.mesh824283698001.geometry}
            material={materials["mat21.002"]}
          />
          <mesh
            name="mesh824283698001_1"
            geometry={nodes.mesh824283698001_1.geometry}
            material={materials["mat20.001"]}
          />
          <mesh
            name="mesh824283698001_2"
            geometry={nodes.mesh824283698001_2.geometry}
            material={materials["mat12.002"]}
          />
        </group>
        <group
          name="group624951879001"
          position={[-0.688, 8.709, -9.035]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh624951879001"
            geometry={nodes.mesh624951879001.geometry}
            material={materials.mat9}
          />
          <mesh
            name="mesh624951879001_1"
            geometry={nodes.mesh624951879001_1.geometry}
            material={materials["mat21.002"]}
          />
        </group>
        <group
          name="group59889140003"
          position={[-0.901, 8.709, -9.035]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh59889140003"
            geometry={nodes.mesh59889140003.geometry}
            material={materials["mat17.002"]}
          />
          <mesh
            name="mesh59889140003_1"
            geometry={nodes.mesh59889140003_1.geometry}
            material={materials["mat21.002"]}
          />
        </group>
        <group
          name="group59889140004"
          position={[-5.603, 1.695, 7.509]}
          rotation={[0, 0.208, -Math.PI / 2]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh59889140004"
            geometry={nodes.mesh59889140004.geometry}
            material={materials["mat17.002"]}
          />
          <mesh
            name="mesh59889140004_1"
            geometry={nodes.mesh59889140004_1.geometry}
            material={materials["mat21.002"]}
          />
        </group>
        <group
          name="group519634257002"
          position={[-5.735, 1.695, 7.4]}
          rotation={[0, 0.208, -Math.PI / 2]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh519634257002"
            geometry={nodes.mesh519634257002.geometry}
            material={materials["mat21.002"]}
          />
          <mesh
            name="mesh519634257002_1"
            geometry={nodes.mesh519634257002_1.geometry}
            material={materials["mat8.001"]}
          />
          <mesh
            name="mesh519634257002_2"
            geometry={nodes.mesh519634257002_2.geometry}
            material={materials["mat23.001"]}
          />
        </group>
        <group
          name="group1274572461002"
          position={[-5.603, 1.695, 7.4]}
          rotation={[0, -0.18, -Math.PI / 2]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh1274572461002"
            geometry={nodes.mesh1274572461002.geometry}
            material={materials["mat12.002"]}
          />
          <mesh
            name="mesh1274572461002_1"
            geometry={nodes.mesh1274572461002_1.geometry}
            material={materials["mat21.002"]}
          />
        </group>
        <group
          name="group59889140005"
          position={[-5.603, 1.481, 7.4]}
          rotation={[0, 0.208, -Math.PI / 2]}
          scale={[19.349, 21.149, 19.349]}
        >
          <mesh
            name="mesh59889140005"
            geometry={nodes.mesh59889140005.geometry}
            material={materials["mat17.002"]}
          />
          <mesh
            name="mesh59889140005_1"
            geometry={nodes.mesh59889140005_1.geometry}
            material={materials["mat21.002"]}
          />
        </group>
        <group
          name="group1222719261001"
          position={[-2.317, 2.714, 7.631]}
          rotation={[-Math.PI, 1.061, -Math.PI]}
          scale={[4.557, 6.162, 4.557]}
        >
          <mesh
            name="mesh1222719261001"
            geometry={nodes.mesh1222719261001.geometry}
            material={materials["mat16.001"]}
          />
          <mesh
            name="mesh1222719261001_1"
            geometry={nodes.mesh1222719261001_1.geometry}
            material={materials.mat15}
          />
          <mesh
            name="mesh1222719261001_2"
            geometry={nodes.mesh1222719261001_2.geometry}
            material={materials.mat20}
          />
          <mesh
            name="mesh1222719261001_3"
            geometry={nodes.mesh1222719261001_3.geometry}
            material={materials.mat12}
          />
        </group>
        <mesh
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={materials["Wood Pillars"]}
          position={[-2.076, 1.437, 9.111]}
        />
        <mesh
          name="Cube002"
          geometry={nodes.Cube002.geometry}
          material={nodes.Cube002.material}
          position={[9.629, -1.289, -0.015]}
          scale={0.383}
        />
        <mesh
          name="Cube003"
          geometry={nodes.Cube003.geometry}
          material={materials["Wood Pillars"]}
          position={[-7.078, 1.565, 8.978]}
          scale={[1, 0.031, 0.402]}
        />
        <group position={[-0.792, 1.565, 8.978]} scale={[1, 0.031, 0.402]}>
          <mesh
            name="Cube006"
            geometry={nodes.Cube006.geometry}
            material={materials["Wood Pillars"]}
          />
          {shelf === "noShelf" ? (
            <Html
              position={[0.5, 142.677529555501346, 5.484598656207786]}
              className="html-style"
            >
              <div onClick={() => setShelf("shelf1")} className="games-label">
                Games
              </div>
            </Html>
          ) : (
            <Html
              position={[7.2, 255.677529555501346, 5.484598656207786]}
              className="html-style"
            >
              <div onClick={() => setShelf("noShelf")} className="back-label">
                Go Back
              </div>
            </Html>
          )}
        </group>
        <mesh
          name="Cube005"
          geometry={nodes.Cube005.geometry}
          material={materials["Wood Pillars"]}
          position={[-2.617, 0.204, 1.788]}
        />
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={materials["Stone Walls"]}
          position={[0, 5.733, 0]}
          scale={[9, 5.5, 9]}
        />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials.Carpet}
          position={[8, 0.477, -0.136]}
        />
        <mesh
          name="Cube008"
          geometry={nodes.Cube008.geometry}
          material={materials["Stone Walls"]}
          position={[-9.486, 1.437, 0]}
          scale={[1.25, 1, 3.6]}
        />
        <mesh
          name="Cube009"
          geometry={nodes.Cube009.geometry}
          material={materials["Material.005"]}
          position={[-5.228, -0.054, -0.003]}
          scale={[0.417, 1.017, 1]}
        />
        <mesh
          name="Cube010"
          geometry={nodes.Cube010.geometry}
          material={materials["Stone Walls"]}
          position={[0.01, 0, 0]}
        />
        <mesh
          name="Cube011"
          geometry={nodes.Cube011.geometry}
          material={materials["Stone Walls"]}
          position={[0.01, 0, 0]}
        />
        <mesh
          name="Cube012"
          geometry={nodes.Cube012.geometry}
          material={materials["Stone Walls"]}
        />
        <mesh
          name="Cube013"
          geometry={nodes.Cube013.geometry}
          material={materials["Stone Walls"]}
        />
        <mesh
          name="Cube014"
          geometry={nodes.Cube014.geometry}
          material={materials["Stone Walls"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/library222.glb");
